### ISSUE TITLE
Shows texture lines between background images

### ISSUE THREAD

**Issue by drakar** [blackrack/Scatterer#2]
I running KSP.x86_64 on Ubuntu 14.04LTS

This happens: 

![screenshot0](https://cloud.githubusercontent.com/assets/773062/8149417/5cf92a1e-1277-11e5-8b58-28608ba69a09.png)

**Comment by blackrack** [comment]
This is fixed by forcing anisotropic filtering off (there's a button for it in the mod UI). ALso make sure it's not forced on by your drivers.
